# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mK8Aes8duTm3sFmBFkkq6Sc74boZybok
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""read data"""

data = pd.read_csv("/content/Unemployment in India.csv")

print(data.head())

data.tail()

"""return tuple of shape (rows, columns) of data frame"""

data.shape

data.info

print(data.describe)

"""see if this dataset contains missing values or not

"""

print(data.isnull().sum())

x= data['Region'] #plotting column 'region'on x axis

print(x)

y= data[' Estimated Unemployment Rate (%)'] #plotting column ' Estimated Unemployment Rate' on y axis

print(y)

# Assuming df is your DataFrame
# Replace NaN values with a specific value (e.g., 0)
data.fillna(0, inplace=True)

print(data.fillna)

# Remove rows with missing values
data.dropna(inplace=True)

print(data.dropna)

# Interpolate missing values
data.interpolate(inplace=True)

print(data.interpolate)

data2=data.iloc[:,3]

data2

"""look at the correlation b/w the features of this dataset"""

plt.style.use("seaborn-whitegrid")
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

"""rename all the colomns"""

data.columns = ["Date","Region","Frequency","Estimated Unemployment Rate",
               "Estimated Employed","Estimated Labour Participation Rate",
                "Area"]

print(data)

look at the estimated number of employees according to different regions of india

data.columns = ["Date","Region","Frequency","Estimated Unemployment Rate",
               "Estimated Employed","Estimated Labour Participation Rate",
                "Area"]
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Employed",hue="Region",data=data)
plt.show()

"""see the unemployment rate according to different regionsof India"""

plt.figure(figsize=(12,10))
plt.title("Indian Unemployment Rate")
sns.histplot(x="Estimated Unemployment Rate",hue="Region",data=data)
plt.show()

"""create a dashboard analyze the unemployment rate of each Indian state by region use sunburst plot"""

Unemploment = data[["Area","Region","Estimated Unemployment Rate"]]
figure = px.sunburst(Unemploment,path=["Region","Area"],
                      values="Estimated Unemployment Rate",
                      width=700,height=700, color_continuous_scale="RdY1Gn",
                      title="Unemployment Rate in Indian")
plt.show()
figure.show()